### ISSUE TITLE
What is Jacobi?

### ISSUE THREAD

**Issue by rveltz** [tkf/Bifurcations.jl#11]
Hi,

It is probably a silly question but `] add https://github.com/tkf/Bifurcations.jl` leads to this 

```julia
ERROR: Unsatisfiable requirements detected for package Jacobi [83f21c0b]:
 Jacobi [83f21c0b] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0] or uninstalled
 ├─restricted to versions * by Bifurcations [0487d830], leaving only versions [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0]
 │ └─Bifurcations [0487d830] log:
 │   ├─possible versions are: 0.0.1 or uninstalled
 │   └─Bifurcations [0487d830] is fixed to version 0.0.1
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
I then installed your package `Jacobi` and it went smoothly.

**Comment by tkf** [comment]
Oh no, it's not a silly question.  It's surprising you find the answer :)

It requires my fork of `Jacobi` because the original one supports up to 0.6 https://github.com/pjabardo/Jacobi.jl/pull/2.  There are probably other packages to compute Gaussian quadrature and Lagrangian interpolation so I need to find one (or just copy the source code).  There are other things that got old in Bifurcations.jl.  I'll be updating it.

**Comment by rveltz** [comment]
well not completely...

**Comment by tkf** [comment]
I think the current `master` branch works now with the simple standard installation.  I'll close this issue but let me know if you find other or related issues.
